### ISSUE TITLE
KeyError at line 18, Changed 'Content-Type' to 'content-type'

### ISSUE THREAD

**Issue by akash2099** [srcecde/aws-tutorial-code#3]
#### **[ERROR] KeyError: 'Content-Type'Traceback (most recent call last):  File "/var/task/lambda_function.py", line 13, in lambda_handler    content_type = event["headers"]['Content-Type']**

After print(event) , I noticed that it should be 'content-type' not 'Content-Type'.

_Great tutorial on API Gateway on Youtube. Love it._

**Comment by srcecde** [comment]
This is resolved.
